---

# Gitlab CI for 'universal wrapper pipeline settings' project:
# https://github.com/alexanderbazhenoff/universal-wrapper-pipeline-settings

stages:
  - yamllint

yamllint:
  stage: yamllint
  rules:
    - if: '$CI_COMMIT_MESSAGE !~ /^(?i)WIP(.?)*/ && $CI_PIPELINE_SOURCE == "push"'
      when: always
  tags:
    - ansible-lint
  before_script:
    - yamllint -v
  script:
    - yamllint -s -f colored .
