---
YAML_V8R_FILTER_REGEX_EXCLUDE: .+-lint.yml
ACTION_ACTIONLINT_FILTER_REGEX_EXCLUDE: action.yml
DISABLE_LINTERS:
  - REPOSITORY_KICS
  - SPELL_CSPELL
MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: README_RUS.md
