---

name: My composite action
description: Create $WORKFLOW_VARIABLE $JOB_VARIABLE
runs:
  using: composite
  steps:
    - name: Checkout UWP settings repository branch ${{ env.UWP_SETTINGS_BRANCH }}
      uses: actions/checkout@v4
      with:
        repository: alexanderbazhenoff/universal-wrapper-pipeline-settings
        ref: ${{ env.UWP_SETTINGS_BRANCH }}
    - name: Checkout UWP for Jenkins repository branch ${{ env.UWP_JENKINS_BRANCH }}
      uses: actions/checkout@v4
      with:
        repository: alexanderbazhenoff/jenkins-universal-wrapper-pipeline
        ref: ${{ env.UWP_JENKINS_BRANCH }}
        path: jenkins_src
    - name: print values
      run: |
        mkdir wiki_${CI_WIKI_LANG}
        pwd
        ls -lh
      shell: bash
