---

name: Build Wiki composite action
description: Build Wiki docs for specified language

inputs:
  token:
    description: Key for Wiki push
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4
      with:
        repository: alexanderbazhenoff/universal-wrapper-pipeline-settings
        ref: ${{ env.UWP_SETTINGS_BRANCH }}

    - uses: actions/checkout@v4
      with:
        repository: alexanderbazhenoff/jenkins-universal-wrapper-pipeline
        ref: ${{ env.UWP_JENKINS_BRANCH }}
        path: jenkins_src

    - uses: actions/checkout@v4
      with:
        repository: ${{ env.CI_WIKI_REPO }}
        ref: master
        path: wiki_${{ env.CI_WIKI_LANG }}
        token: ${{ inputs.token }}

    - run: python3 .github/workflows/docs_parser.py
      shell: bash

    - run: |
        cd wiki_${{ env.CI_WIKI_LANG }}
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add *.md
        git commit -m "Automated Wiki Update"
        git push --prune https://token:$token@github.com/${CI_WIKI_REPO}.git
      shell: bash