---

# markdown lint settings for 'Universal Wrapper Pipeline Settings':
# https://github.com/alexanderbazhenoff/universal-wrapper-pipeline-settings

# Default state for all rules
default: True

# Path to configuration file to extend
extends: null

# MD001/heading-increment: Heading levels should only increment by one level at a time
MD001: False

# MD007/ul-indent: Unordered list indentation
MD007: False

# MD009/no-trailing-spaces: Trailing spaces : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md009.md
MD009:
  # Spaces for line break
  br_spaces: 2
  # Allow spaces for empty lines in list items
  list_item_empty_lines: False
  # Include unnecessary breaks
  strict: False

# MD013/line-length: Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include tables
  tables: False
  # Include headings
  headings: False

# MD012/no-multiple-blanks: Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 2

# MD025/single-title/single-h1 Multiple top-level headings in the same document
MD025: False